# Example cria config.yaml
# Copy this file to ~/.config/cria/config.yaml and edit as needed
api_url: "https://vikunja.example.com/api/v1"

# Option 1: API key directly in config (less secure)
api_key: "your-api-key-here"

# Option 2: API key from file (more secure)
# api_key_file: "~/.config/cria/api_key"
# api_key_file: "/path/to/api/key/file"
# api_key_file: "api_key"  # relative to ~/.config/cria/

# If both api_key and api_key_file are set, api_key takes precedence

default_project: "Inbox"

# Quick actions for fast task modification
# Press Space followed by the configured key to trigger the action
quick_actions:
  - key: "w"
    action: "project"
    target: "Work"
  - key: "p"
    action: "project"
    target: "Personal"
  - key: "h"
    action: "project"
    target: "Home"
  - key: "u"
    action: "priority"
    target: "5"    # u for urgent (priority 5)
  - key: "l"
    action: "priority"
    target: "1"    # l for low priority
  - key: "m"
    action: "priority"
    target: "3"    # m for medium priority
  - key: "i"
    action: "label"
    target: "Important"
  - key: "t"
    action: "label"
    target: "Today"
