api_url: https://tasks.fluffy-rooster.ts.net
api_key_file: /home/justin/.config/sops-nix/secrets/vikunja_api_key
default_project: Inbox
quick_actions:
- key: w
  action: project
  target: Western
column_layouts:
  - name: "default"
    description: "My personal workflow layout"
    columns: 
      - name: "Priority"
        column_type: "Priority"
        min_width: 3
        max_width: 6
        enabled: true
      - name: "Task"
        column_type: "Title"
        min_width: 30
        wrap_text: true
        enabled: true
      - name: "Project"
        column_type: "Project"
        min_width: 12
        max_width: 18
        enabled: true
      - name: "Due"
        column_type: "DueDate"
        min_width: 10
        max_width: 12
        enabled: true
      - name: "Labels"
        column_type: "Labels"
        min_width: 8
        max_width: 20
        wrap_text: true
        enabled: true

  - name: "minimal"
    description: "Minimal view for focused work"
    columns:
      - name: "Task"
        column_type: "Title"
        min_width: 40
        wrap_text: true
        enabled: true
      - name: "Due"
        column_type: "DueDate"
        min_width: 10
        max_width: 12
        enabled: true
      - name: "Priority"
        column_type: "Priority"
        min_width: 3
        max_width: 6
        enabled: true

  - name: "timeline"
    description: "Time-focused view with dates"
    columns:
      - name: "Priority"
        column_type: "Priority"
        min_width: 3
        max_width: 6
        enabled: true
      - name: "Task"
        column_type: "Title"
        min_width: 25
        wrap_text: true
        enabled: true
      - name: "Start"
        column_type: "StartDate"
        min_width: 10
        max_width: 12
        enabled: true
      - name: "Due"
        column_type: "DueDate"
        min_width: 10
        max_width: 12
        enabled: true
      - name: "Created"
        column_type: "Created"
        min_width: 10
        max_width: 12
        enabled: true
      - name: "Project"
        column_type: "Project"
        min_width: 10
        max_width: 15
        enabled: true

  - name: "team"
    description: "Team collaboration view"
    columns:
      - name: "Priority"
        column_type: "Priority"
        min_width: 3
        max_width: 6
        enabled: true
      - name: "Task"
        column_type: "Title"
        min_width: 25
        wrap_text: true
        enabled: true
      - name: "Assignees"
        column_type: "Assignees"
        min_width: 10
        max_width: 20
        wrap_text: true
        enabled: true
      - name: "Status"
        column_type: "Status"
        min_width: 8
        max_width: 10
        enabled: true
      - name: "Project"
        column_type: "Project"
        min_width: 10
        max_width: 15
        enabled: true
      - name: "Due"
        column_type: "DueDate"
        min_width: 10
        max_width: 12
        enabled: true

  - name: "labels-focus"
    description: "Label and categorization focus"
    columns:
      - name: "Priority"
        column_type: "Priority"
        min_width: 3
        max_width: 6
        enabled: true
      - name: "Task"
        column_type: "Title"
        min_width: 20
        wrap_text: true
        enabled: true
      - name: "Labels"
        column_type: "Labels"
        min_width: 15
        max_width: 30
        wrap_text: true
        enabled: true
      - name: "Project"
        column_type: "Project"
        min_width: 10
        max_width: 15
        enabled: true
      - name: "Due"
        column_type: "DueDate"
        min_width: 10
        max_width: 12
        enabled: true

  - name: "compact"
    description: "Ultra-compact for small screens"
    columns:
      - name: "Task"
        column_type: "Title"
        min_width: 35
        wrap_text: true
        enabled: true
      - name: "Due"
        column_type: "DueDate"
        min_width: 8
        max_width: 10
        enabled: true

  - name: "full-detail"
    description: "All available information"
    columns:
      - name: "Priority"
        column_type: "Priority"
        min_width: 3
        max_width: 6
        enabled: true
      - name: "Task"
        column_type: "Title"
        min_width: 20
        wrap_text: true
        enabled: true
      - name: "Project"
        column_type: "Project"
        min_width: 8
        max_width: 15
        enabled: true
      - name: "Status"
        column_type: "Status"
        min_width: 6
        max_width: 8
        enabled: true
      - name: "Start"
        column_type: "StartDate"
        min_width: 8
        max_width: 10
        enabled: true
      - name: "Due"
        column_type: "DueDate"
        min_width: 8
        max_width: 10
        enabled: true
      - name: "Labels"
        column_type: "Labels"
        min_width: 8
        max_width: 20
        wrap_text: true
        enabled: true
      - name: "Assignees"
        column_type: "Assignees"
        min_width: 8
        max_width: 15
        wrap_text: true
        enabled: true
      - name: "Created"
        column_type: "Created"
        min_width: 8
        max_width: 10
        enabled: true
      - name: "Updated"
        column_type: "Updated"
        min_width: 8
        max_width: 10
        enabled: true

active_layout: "default"
